// frontend/src/app/components/admin-content.tsx
import { useState } from 'react';
import { Search, Plus, Edit2, Trash2, Star, Eye, Filter, Download } from 'lucide-react';
import { Button } from '@/app/components/ui/button';
import { Card } from '@/app/components/ui/card';
import { Badge } from '@/app/components/ui/badge';
import { Input } from '@/app/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/app/components/ui/table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/app/components/ui/select';

interface Content {
  id: string;
  title: string;
  platform: string;
  genre: string;
  rating: number;
  views: number;
  status: 'active' | 'hidden' | 'scheduled';
  hiddenGem: boolean;
  releaseDate: string;
}

const mockContent: Content[] = [
  {
    id: '1',
    title: 'Cosmic Odyssey',
    platform: 'Netflix',
    genre: 'Sci-Fi',
    rating: 4.8,
    views: 245000,
    status: 'active',
    hiddenGem: true,
    releaseDate: '2026-01-15',
  },
  {
    id: '2',
    title: 'The Last Kingdom',
    platform: 'Prime Video',
    genre: 'Drama',
    rating: 4.6,
    views: 189000,
    status: 'active',
    hiddenGem: false,
    releaseDate: '2026-01-20',
  },
  {
    id: '3',
    title: 'Midnight Tales',
    platform: 'Disney+',
    genre: 'Horror',
    rating: 4.3,
    views: 156000,
    status: 'hidden',
    hiddenGem: true,
    releaseDate: '2026-01-10',
  },
  {
    id: '4',
    title: 'Summer Dreams',
    platform: 'Hulu',
    genre: 'Romance',
    rating: 4.5,
    views: 201000,
    status: 'active',
    hiddenGem: false,
    releaseDate: '2026-02-01',
  },
  {
    id: '5',
    title: 'Dark Waters',
    platform: 'HBO Max',
    genre: 'Thriller',
    rating: 4.7,
    views: 178000,
    status: 'scheduled',
    hiddenGem: true,
    releaseDate: '2026-02-15',
  },
];

export function AdminContent() {
  const [searchQuery, setSearchQuery] = useState('');
  const [filterPlatform, setFilterPlatform] = useState('all');
  const [filterStatus, setFilterStatus] = useState('all');
  const [content] = useState<Content[]>(mockContent);

  const filteredContent = content.filter((item) => {
    const matchesSearch = item.title.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesPlatform = filterPlatform === 'all' || item.platform === filterPlatform;
    const matchesStatus = filterStatus === 'all' || item.status === filterStatus;
    return matchesSearch && matchesPlatform && matchesStatus;
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active':
        return 'bg-green-500/20 text-green-500 border-green-500';
      case 'hidden':
        return 'bg-gray-500/20 text-gray-400 border-gray-400';
      case 'scheduled':
        return 'bg-blue-500/20 text-blue-500 border-blue-500';
      default:
        return 'bg-gray-500/20 text-gray-400 border-gray-400';
    }
  };

  return (
    <div className="space-y-6 p-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-3xl text-white mb-2">Content Management</h1>
          <p className="text-gray-400">Manage streaming titles, metadata, and featured content</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline" className="border-[#8B5CF6] text-[#8B5CF6] hover:bg-[#8B5CF6]/10">
            <Download className="w-4 h-4 mr-2" />
            Export
          </Button>
          <Button className="bg-[#8B5CF6] hover:bg-[#7C3AED] text-white">
            <Plus className="w-4 h-4 mr-2" />
            Add Content
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="bg-[#141920] border-[#8B5CF6]/20 p-6">
          <div className="flex items-center justify-between mb-2">
            <p className="text-gray-400">Total Content</p>
            <div className="p-2 bg-[#8B5CF6]/20 rounded-lg">
              <Eye className="w-4 h-4 text-[#8B5CF6]" />
            </div>
          </div>
          <p className="text-3xl text-white">{content.length}</p>
          <p className="text-sm text-green-500 mt-1">+12% this month</p>
        </Card>
        <Card className="bg-[#141920] border-[#8B5CF6]/20 p-6">
          <div className="flex items-center justify-between mb-2">
            <p className="text-gray-400">Active</p>
            <div className="p-2 bg-green-500/20 rounded-lg">
              <Star className="w-4 h-4 text-green-500" />
            </div>
          </div>
          <p className="text-3xl text-white">{content.filter((c) => c.status === 'active').length}</p>
          <p className="text-sm text-gray-400 mt-1">Currently streaming</p>
        </Card>
        <Card className="bg-[#141920] border-[#8B5CF6]/20 p-6">
          <div className="flex items-center justify-between mb-2">
            <p className="text-gray-400">Hidden Gems</p>
            <div className="p-2 bg-yellow-500/20 rounded-lg">
              <Star className="w-4 h-4 text-yellow-500" />
            </div>
          </div>
          <p className="text-3xl text-white">{content.filter((c) => c.hiddenGem).length}</p>
          <p className="text-sm text-gray-400 mt-1">Featured selections</p>
        </Card>
        <Card className="bg-[#141920] border-[#8B5CF6]/20 p-6">
          <div className="flex items-center justify-between mb-2">
            <p className="text-gray-400">Total Views</p>
            <div className="p-2 bg-[#EC4899]/20 rounded-lg">
              <Eye className="w-4 h-4 text-[#EC4899]" />
            </div>
          </div>
          <p className="text-3xl text-white">
            {(content.reduce((sum, c) => sum + c.views, 0) / 1000).toFixed(0)}K
          </p>
          <p className="text-sm text-green-500 mt-1">+8% this week</p>
        </Card>
      </div>

      {/* Filters */}
      <Card className="bg-[#141920] border-[#8B5CF6]/20 p-6">
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-1">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <Input
                type="text"
                placeholder="Search content..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10 bg-[#0B0E14] border-[#8B5CF6]/20 text-white"
              />
            </div>
          </div>
          <Select value={filterPlatform} onValueChange={setFilterPlatform}>
            <SelectTrigger className="w-full md:w-48 bg-[#0B0E14] border-[#8B5CF6]/20 text-white">
              <Filter className="w-4 h-4 mr-2 text-gray-400" />
              <SelectValue placeholder="Platform" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Platforms</SelectItem>
              <SelectItem value="Netflix">Netflix</SelectItem>
              <SelectItem value="Prime Video">Prime Video</SelectItem>
              <SelectItem value="Disney+">Disney+</SelectItem>
              <SelectItem value="Hulu">Hulu</SelectItem>
              <SelectItem value="HBO Max">HBO Max</SelectItem>
            </SelectContent>
          </Select>
          <Select value={filterStatus} onValueChange={setFilterStatus}>
            <SelectTrigger className="w-full md:w-48 bg-[#0B0E14] border-[#8B5CF6]/20 text-white">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Status</SelectItem>
              <SelectItem value="active">Active</SelectItem>
              <SelectItem value="hidden">Hidden</SelectItem>
              <SelectItem value="scheduled">Scheduled</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </Card>

      {/* Content Table */}
      <Card className="bg-[#141920] border-[#8B5CF6]/20 overflow-hidden">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow className="border-[#8B5CF6]/20 hover:bg-transparent">
                <TableHead className="text-gray-400">Title</TableHead>
                <TableHead className="text-gray-400">Platform</TableHead>
                <TableHead className="text-gray-400">Genre</TableHead>
                <TableHead className="text-gray-400">Rating</TableHead>
                <TableHead className="text-gray-400">Views</TableHead>
                <TableHead className="text-gray-400">Status</TableHead>
                <TableHead className="text-gray-400">Release Date</TableHead>
                <TableHead className="text-gray-400 text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredContent.map((item) => (
                <TableRow key={item.id} className="border-[#8B5CF6]/20 hover:bg-[#8B5CF6]/5">
                  <TableCell>
                    <div className="flex items-center gap-3">
                      <div className="text-white">{item.title}</div>
                      {item.hiddenGem && (
                        <Badge className="bg-yellow-500/20 text-yellow-500 border-yellow-500">
                          <Star className="w-3 h-3 mr-1" />
                          Hidden Gem
                        </Badge>
                      )}
                    </div>
                  </TableCell>
                  <TableCell className="text-gray-300">{item.platform}</TableCell>
                  <TableCell>
                    <Badge variant="outline" className="border-[#8B5CF6]/30 text-gray-400">
                      {item.genre}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1">
                      <Star className="w-4 h-4 text-yellow-500 fill-yellow-500" />
                      <span className="text-white">{item.rating}</span>
                    </div>
                  </TableCell>
                  <TableCell className="text-gray-300">
                    {(item.views / 1000).toFixed(0)}K
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline" className={getStatusColor(item.status)}>
                      {item.status}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-gray-300">{item.releaseDate}</TableCell>
                  <TableCell>
                    <div className="flex items-center justify-end gap-2">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="text-gray-400 hover:text-[#8B5CF6] hover:bg-[#8B5CF6]/10"
                      >
                        <Edit2 className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="text-gray-400 hover:text-red-500 hover:bg-red-500/10"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </Card>
    </div>
  );
}

// frontend/src/app/components/admin-content/admin-content.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  LucideAngularModule,
  Search,
  Plus,
  Edit2,
  Trash2,
  Star,
  Eye,
  Filter,
  Download,
} from 'lucide-angular';

interface Content {
  id: string;
  title: string;
  platform: string;
  genre: string;
  rating: number;
  views: number;
  status: 'active' | 'hidden' | 'scheduled';
  hiddenGem: boolean;
  releaseDate: string;
}

@Component({
  selector: 'app-admin-content',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  templateUrl: './admin-content.component.html',
  styleUrls: ['./admin-content.component.css'],
})
export class AdminContentComponent {
  readonly SearchIcon = Search;
  readonly PlusIcon = Plus;
  readonly Edit2Icon = Edit2;
  readonly Trash2Icon = Trash2;
  readonly StarIcon = Star;
  readonly EyeIcon = Eye;
  readonly FilterIcon = Filter;
  readonly DownloadIcon = Download;

  searchQuery = signal('');
  filterPlatform = signal('all');
  filterStatus = signal('all');

  content: Content[] = [
    {
      id: '1',
      title: 'Cosmic Odyssey',
      platform: 'Netflix',
      genre: 'Sci-Fi',
      rating: 4.8,
      views: 245000,
      status: 'active',
      hiddenGem: true,
      releaseDate: '2026-01-15',
    },
    {
      id: '2',
      title: 'The Last Kingdom',
      platform: 'Prime Video',
      genre: 'Drama',
      rating: 4.6,
      views: 189000,
      status: 'active',
      hiddenGem: false,
      releaseDate: '2026-01-20',
    },
    {
      id: '3',
      title: 'Midnight Tales',
      platform: 'Disney+',
      genre: 'Horror',
      rating: 4.3,
      views: 156000,
      status: 'hidden',
      hiddenGem: true,
      releaseDate: '2026-01-10',
    },
    {
      id: '4',
      title: 'Summer Dreams',
      platform: 'Hulu',
      genre: 'Romance',
      rating: 4.5,
      views: 201000,
      status: 'active',
      hiddenGem: false,
      releaseDate: '2026-02-01',
    },
    {
      id: '5',
      title: 'Dark Waters',
      platform: 'HBO Max',
      genre: 'Thriller',
      rating: 4.7,
      views: 178000,
      status: 'scheduled',
      hiddenGem: true,
      releaseDate: '2026-02-15',
    },
  ];

  get filteredContent(): Content[] {
    return this.content.filter((item) => {
      const matchesSearch = item.title.toLowerCase().includes(this.searchQuery().toLowerCase());
      const matchesPlatform = this.filterPlatform() === 'all' || item.platform === this.filterPlatform();
      const matchesStatus = this.filterStatus() === 'all' || item.status === this.filterStatus();
      return matchesSearch && matchesPlatform && matchesStatus;
    });
  }

  get activeCount(): number {
    return this.content.filter((c) => c.status === 'active').length;
  }

  get hiddenGemsCount(): number {
    return this.content.filter((c) => c.hiddenGem).length;
  }

  get averageRating(): number {
    const total = this.content.reduce((sum, c) => sum + c.rating, 0);
    return Math.round((total / this.content.length) * 10) / 10;
  }

  getStatusColor(status: string): string {
    switch (status) {
      case 'active':
        return 'bg-green-500/20 text-green-500 border-green-500';
      case 'hidden':
        return 'bg-gray-500/20 text-gray-400 border-gray-400';
      case 'scheduled':
        return 'bg-blue-500/20 text-blue-500 border-blue-500';
      default:
        return 'bg-gray-500/20 text-gray-400 border-gray-400';
    }
  }
}

<div class="space-y-6 p-6 max-w-7xl mx-auto">
  <!-- Header -->
  <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
    <div>
      <h1 class="text-3xl text-white mb-2">Content Management</h1>
      <p class="text-gray-400">Manage streaming titles, metadata, and featured content</p>
    </div>
    <div class="flex gap-3">
      <button class="flex items-center gap-2 px-4 py-2 border border-[#8B5CF6] text-[#8B5CF6] hover:bg-[#8B5CF6]/10 rounded-lg transition-all">
        <lucide-icon [img]="DownloadIcon" class="w-4 h-4"></lucide-icon>
        Export
      </button>
      <button class="flex items-center gap-2 px-4 py-2 bg-[#8B5CF6] hover:bg-[#7C3AED] text-white rounded-lg transition-all">
        <lucide-icon [img]="PlusIcon" class="w-4 h-4"></lucide-icon>
        Add Content
      </button>
    </div>
  </div>

  <!-- Stats Cards -->
  <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
    <div class="bg-[#141920] border border-[#8B5CF6]/20 rounded-lg p-6">
      <div class="flex items-center justify-between mb-2">
        <p class="text-gray-400">Total Content</p>
        <div class="p-2 bg-[#8B5CF6]/20 rounded-lg">
          <lucide-icon [img]="EyeIcon" class="w-4 h-4 text-[#8B5CF6]"></lucide-icon>
        </div>
      </div>
      <p class="text-3xl text-white">{{ content.length }}</p>
      <p class="text-sm text-green-500 mt-1">+12% this month</p>
    </div>
    
    <div class="bg-[#141920] border border-[#8B5CF6]/20 rounded-lg p-6">
      <div class="flex items-center justify-between mb-2">
        <p class="text-gray-400">Active</p>
        <div class="p-2 bg-green-500/20 rounded-lg">
          <lucide-icon [img]="StarIcon" class="w-4 h-4 text-green-500"></lucide-icon>
        </div>
      </div>
      <p class="text-3xl text-white">{{ activeCount }}</p>
      <p class="text-sm text-gray-400 mt-1">Currently streaming</p>
    </div>
    
    <div class="bg-[#141920] border border-[#8B5CF6]/20 rounded-lg p-6">
      <div class="flex items-center justify-between mb-2">
        <p class="text-gray-400">Hidden Gems</p>
        <div class="p-2 bg-[#EC4899]/20 rounded-lg">
          <lucide-icon [img]="StarIcon" class="w-4 h-4 text-[#EC4899]"></lucide-icon>
        </div>
      </div>
      <p class="text-3xl text-white">{{ hiddenGemsCount }}</p>
      <p class="text-sm text-gray-400 mt-1">Curated picks</p>
    </div>
    
    <div class="bg-[#141920] border border-[#8B5CF6]/20 rounded-lg p-6">
      <div class="flex items-center justify-between mb-2">
        <p class="text-gray-400">Avg. Rating</p>
        <div class="p-2 bg-yellow-500/20 rounded-lg">
          <lucide-icon [img]="StarIcon" class="w-4 h-4 text-yellow-500"></lucide-icon>
        </div>
      </div>
      <p class="text-3xl text-white">{{ averageRating }}</p>
      <p class="text-sm text-gray-400 mt-1">Out of 5.0</p>
    </div>
  </div>

  <!-- Filters -->
  <div class="bg-[#141920] border border-[#8B5CF6]/20 rounded-lg p-6">
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
      <div class="relative">
        <lucide-icon [img]="SearchIcon" class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"></lucide-icon>
        <input
          type="text"
          placeholder="Search content..."
          [(ngModel)]="searchQuery"
          (ngModelChange)="searchQuery.set($event)"
          class="w-full pl-10 pr-4 py-2 bg-[#0B0E14] border border-[#8B5CF6]/30 rounded-lg text-white placeholder-gray-400 focus:outline-none focus:border-[#8B5CF6]"
        />
      </div>
      
      <select
        [(ngModel)]="filterPlatform"
        (ngModelChange)="filterPlatform.set($event)"
        class="px-4 py-2 bg-[#0B0E14] border border-[#8B5CF6]/30 rounded-lg text-white focus:outline-none focus:border-[#8B5CF6]">
        <option value="all">All Platforms</option>
        <option value="Netflix">Netflix</option>
        <option value="Prime Video">Prime Video</option>
        <option value="Disney+">Disney+</option>
        <option value="Hulu">Hulu</option>
        <option value="HBO Max">HBO Max</option>
      </select>
      
      <select
        [(ngModel)]="filterStatus"
        (ngModelChange)="filterStatus.set($event)"
        class="px-4 py-2 bg-[#0B0E14] border border-[#8B5CF6]/30 rounded-lg text-white focus:outline-none focus:border-[#8B5CF6]">
        <option value="all">All Status</option>
        <option value="active">Active</option>
        <option value="hidden">Hidden</option>
        <option value="scheduled">Scheduled</option>
      </select>
      
      <button class="flex items-center justify-center gap-2 px-4 py-2 border border-[#8B5CF6]/30 text-gray-400 hover:text-white hover:border-[#8B5CF6] rounded-lg transition-all">
        <lucide-icon [img]="FilterIcon" class="w-4 h-4"></lucide-icon>
        More Filters
      </button>
    </div>
  </div>

  <!-- Content Table -->
  <div class="bg-[#141920] border border-[#8B5CF6]/20 rounded-lg overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full">
        <thead class="bg-[#0B0E14] border-b border-[#8B5CF6]/20">
          <tr>
            <th class="px-6 py-4 text-left text-sm text-gray-400">Title</th>
            <th class="px-6 py-4 text-left text-sm text-gray-400">Platform</th>
            <th class="px-6 py-4 text-left text-sm text-gray-400">Genre</th>
            <th class="px-6 py-4 text-left text-sm text-gray-400">Rating</th>
            <th class="px-6 py-4 text-left text-sm text-gray-400">Views</th>
            <th class="px-6 py-4 text-left text-sm text-gray-400">Status</th>
            <th class="px-6 py-4 text-left text-sm text-gray-400">Release Date</th>
            <th class="px-6 py-4 text-right text-sm text-gray-400">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-[#8B5CF6]/10">
          <tr *ngFor="let item of filteredContent" class="hover:bg-[#0B0E14]/50 transition-colors">
            <td class="px-6 py-4">
              <div class="flex items-center gap-3">
                <div class="text-white">{{ item.title }}</div>
                <span *ngIf="item.hiddenGem" class="px-2 py-0.5 bg-[#EC4899]/20 text-[#EC4899] text-xs rounded border border-[#EC4899]">
                  Hidden Gem
                </span>
              </div>
            </td>
            <td class="px-6 py-4 text-[#8B5CF6]">{{ item.platform }}</td>
            <td class="px-6 py-4 text-gray-400">{{ item.genre }}</td>
            <td class="px-6 py-4">
              <div class="flex items-center gap-1 text-white">
                <lucide-icon [img]="StarIcon" class="w-4 h-4 text-yellow-500 fill-yellow-500"></lucide-icon>
                {{ item.rating }}
              </div>
            </td>
            <td class="px-6 py-4 text-gray-400">{{ item.views | number }}</td>
            <td class="px-6 py-4">
              <span [class]="getStatusColor(item.status)" class="px-2 py-1 text-xs rounded border uppercase">
                {{ item.status }}
              </span>
            </td>
            <td class="px-6 py-4 text-gray-400">{{ item.releaseDate }}</td>
            <td class="px-6 py-4">
              <div class="flex items-center justify-end gap-2">
                <button class="p-2 text-gray-400 hover:text-[#8B5CF6] hover:bg-[#8B5CF6]/10 rounded-lg transition-all">
                  <lucide-icon [img]="Edit2Icon" class="w-4 h-4"></lucide-icon>
                </button>
                <button class="p-2 text-gray-400 hover:text-red-500 hover:bg-red-500/10 rounded-lg transition-all">
                  <lucide-icon [img]="Trash2Icon" class="w-4 h-4"></lucide-icon>
                </button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
